### ISSUE TITLE
i want to know in hog test05b first question s0 how can get 43

### ISSUE THREAD

**Issue by Unic-hou** [syedasif-work/CS61A#1]
2+2+3+4+2+2+2+2 shouldn't be 19?

**Comment by syedasif-work** [comment]
Both players start out at 0. (0, 0)
Player 0 rolls 3 dice and gets 7 points. (7, 0)
Player 1 rolls 1 dice and gets 4 points. (7, 4)
Player 0 rolls 5 dice and gets 10 points. 5 is 2 away from 7, so player 0 gets a bonus of 3. (20, 4)
Player 1 rolls 2 dice and gets 8 points. 2 is 2 away from 4, so player 1 gets a bonus of 3. (20, 15)
Player 0 rolls 8 dice and gets 20 points. 8 is 2 away from 10, so player 0 gets a bonus of 3. (43, 15)

**Comment by Unic-hou** [comment]
Thank you!
